"GET / HTTP/1.1" 200 12111
"GET /static/assets/js/main.js HTTP/1.1" 200 680
"GET /static/assets/js/breakpoints.min.js HTTP/1.1" 200 2439
"GET /static/assets/js/util.js HTTP/1.1" 200 12433
"GET /static/assets/js/browser.min.js HTTP/1.1" 200 1851
"GET /static/assets/css/main.css HTTP/1.1" 200 52986
"GET /static/assets/js/jquery.min.js HTTP/1.1" 200 88145
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 55967
"GET /static/assets/css/images/top-3200.svg HTTP/1.1" 200 893
"GET /static/assets/css/images/overlay.png HTTP/1.1" 200 2105
"GET /static/assets/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13580
"GET /static/images/header.jpg HTTP/1.1" 200 39278
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2576
"GET /play HTTP/1.1" 301 0
Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 314, in playRecording
    sendEmail()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 265, in sendEmail
    email = Bimail('Sales email ' +datetime.now().strftime('%Y/%m/%d'), ['sanika.shah@ibm.com', 'ryan.kelly@ibm.com'])
AttributeError: 'module' object has no attribute 'now'
"GET /play/ HTTP/1.1" 500 69490
"GET / HTTP/1.1" 200 12111
"GET /static/assets/js/browser.min.js HTTP/1.1" 200 1851
"GET /static/assets/js/breakpoints.min.js HTTP/1.1" 200 2439
"GET /static/assets/css/main.css HTTP/1.1" 200 52986
"GET /static/assets/js/main.js HTTP/1.1" 200 680
"GET /static/assets/js/jquery.min.js HTTP/1.1" 200 88145
"GET /static/assets/js/util.js HTTP/1.1" 200 12433
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 55967
"GET /static/assets/css/images/top-1600.svg HTTP/1.1" 200 893
"GET /static/assets/css/images/overlay.png HTTP/1.1" 200 2105
"GET /static/images/header.jpg HTTP/1.1" 200 39278
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2576
"GET /static/assets/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13580
"GET / HTTP/1.1" 200 12111
Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 314, in playRecording
    sendEmail()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 266, in sendEmail
    email.send()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 70, in send
    s.login(self.sender, self.senderpass)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials k5sm9031682ioj.47 - gsmtp')
"GET /play/ HTTP/1.1" 500 80892
"GET /play/ HTTP/1.1" 500 59
- Broken pipe from ('127.0.0.1', 63839)

"GET / HTTP/1.1" 200 12111
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 16384
- Broken pipe from ('127.0.0.1', 64004)

Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2576
- Broken pipe from ('127.0.0.1', 64005)

Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 315, in playRecording
    sendEmail()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 266, in sendEmail
    email.send()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 70, in send
    s.login(self.sender, self.senderpass)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials y17sm5811257ioa.40 - gsmtp')
"GET /play/ HTTP/1.1" 500 81173
"GET / HTTP/1.1" 200 12111
"GET /play/ HTTP/1.1" 200 215
"GET /static/recording.wav HTTP/1.1" 200 1004429
"GET / HTTP/1.1" 200 12111
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 16384
- Broken pipe from ('127.0.0.1', 64637)

Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 322, in playRecording
    watson()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 314, in watson
    con_file=parse.convert()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/parse.py", line 60, in convert
    d = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
"GET /play/ HTTP/1.1" 500 90362
Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 322, in playRecording
    watson()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 314, in watson
    con_file=parse.convert()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/parse.py", line 62, in convert
    d = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
"GET /play/ HTTP/1.1" 500 90645
"GET / HTTP/1.1" 200 12111
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 8192
- Broken pipe from ('127.0.0.1', 64674)

Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 322, in playRecording
    watson()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 314, in watson
    con_file=parse.convert()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/parse.py", line 62, in convert
    d = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
"GET /play/ HTTP/1.1" 500 90510
Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 322, in playRecording
    watson()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 314, in watson
    con_file=parse.convert()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/parse.py", line 63, in convert
    d = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
"GET /play/ HTTP/1.1" 500 90598
"GET / HTTP/1.1" 200 12111
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 8192
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 500 59
- Broken pipe from ('127.0.0.1', 64739)

Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2576
- Broken pipe from ('127.0.0.1', 64740)

Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 322, in playRecording
    watson()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 313, in watson
    parse.parse_audio(path)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/parse.py", line 45, in parse_audio
    with open(audio,'rb') as audio_file:
IOError: [Errno 2] No such file or directory: u'/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/static/recording.wav'
"GET /play/ HTTP/1.1" 500 75596
Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 322, in playRecording
    watson()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 317, in watson
    f.write(i+"\n")
IOError: File not open for writing
"GET /play/ HTTP/1.1" 500 72403
"GET / HTTP/1.1" 200 12111
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 8192
- Broken pipe from ('127.0.0.1', 64778)

Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 322, in playRecording
    watson()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 315, in watson
    with open(path2+'/recording.txt') as f:
IOError: [Errno 2] No such file or directory: u'/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/static/recording.txt'
"GET /play/ HTTP/1.1" 500 71996
"GET / HTTP/1.1" 200 12111
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 16384
- Broken pipe from ('127.0.0.1', 64797)

Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2576
Internal Server Error: /play/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 326, in playRecording
    sendEmail()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 266, in sendEmail
    email.send()
  File "/Users/Ryan.Kelly@ibm.com/Desktop/IBMHackathon/Django/mysite/scrum/views.py", line 70, in send
    s.login(self.sender, self.senderpass)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials k2sm5345466iom.50 - gsmtp')
"GET /play/ HTTP/1.1" 500 81115
"GET /play/ HTTP/1.1" 200 215
"GET /static/recording.mp3 HTTP/1.1" 200 1004429
"GET / HTTP/1.1" 200 12111
"GET /static/assets/js/jquery.min.js HTTP/1.1" 304 0
"GET /static/assets/css/main.css HTTP/1.1" 304 0
"GET /static/assets/js/browser.min.js HTTP/1.1" 304 0
"GET /static/assets/js/util.js HTTP/1.1" 304 0
"GET /static/assets/js/breakpoints.min.js HTTP/1.1" 304 0
"GET /static/assets/js/main.js HTTP/1.1" 304 0
"GET /static/assets/css/fontawesome-all.min.css HTTP/1.1" 200 55967
"GET /static/images/header.jpg HTTP/1.1" 304 0
"GET /static/assets/css/images/overlay.png HTTP/1.1" 304 0
"GET /static/assets/css/images/top-3200.svg HTTP/1.1" 304 0
"GET /static/assets/webfonts/fa-regular-400.woff2 HTTP/1.1" 304 0
"GET /createuser HTTP/1.1" 301 0
"GET /createuser/ HTTP/1.1" 200 26
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1650
"GET /static/admin/css/login.css HTTP/1.1" 200 1203
"GET /static/admin/css/base.css HTTP/1.1" 200 16066
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 2779
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
"GET /play/ HTTP/1.1" 200 215
"GET /static/recording.mp3 HTTP/1.1" 200 1004429
"GET /login HTTP/1.1" 301 0
"GET /login/ HTTP/1.1" 200 2718
"GET /static/css/queries.css HTTP/1.1" 200 1059
"GET /static/css/styles.css HTTP/1.1" 200 23676
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 99961
"GET /static/css/flexslider.css HTTP/1.1" 200 4991
"GET /static/js/bootstrap.min.js HTTP/1.1" 200 29110
"GET /static/js/waypoints.min.js HTTP/1.1" 200 8044
"GET /static/js/scripts.js HTTP/1.1" 200 3224
"GET /static/css/animate.css HTTP/1.1" 200 69747
"GET /static/js/jquery.flexslider.js HTTP/1.1" 200 53436
"GET /static/js/modernizr.js HTTP/1.1" 200 15243
"GET /static/img/hero-bg.jpg HTTP/1.1" 404 1658
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2895
"GET /login/ HTTP/1.1" 200 2718
"GET /static/js/modernizr.js HTTP/1.1" 200 15243
"GET /static/js/jquery.flexslider.js HTTP/1.1" 200 53436
"GET /static/img/hero-bg.jpg HTTP/1.1" 404 1658
"GET /login/ HTTP/1.1" 200 2718
"GET /static/js/waypoints.min.js HTTP/1.1" 304 0
"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/js/scripts.js HTTP/1.1" 304 0
"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/css/flexslider.css HTTP/1.1" 304 0
"GET /static/css/styles.css HTTP/1.1" 304 0
"GET /static/css/queries.css HTTP/1.1" 304 0
"GET /static/css/animate.css HTTP/1.1" 304 0
"GET /static/js/modernizr.js HTTP/1.1" 200 15243
"GET /static/js/jquery.flexslider.js HTTP/1.1" 200 53436
"GET /static/img/hero-bg.jpg HTTP/1.1" 404 1658
"GET /login/ HTTP/1.1" 200 2718
"GET /static/js/modernizr.js HTTP/1.1" 304 0
"GET /static/js/waypoints.min.js HTTP/1.1" 304 0
"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/js/scripts.js HTTP/1.1" 304 0
"GET /static/css/flexslider.css HTTP/1.1" 304 0
"GET /static/js/jquery.flexslider.js HTTP/1.1" 304 0
"GET /static/css/queries.css HTTP/1.1" 304 0
"GET /static/css/animate.css HTTP/1.1" 304 0
"GET /static/css/styles.css HTTP/1.1" 200 23684
"GET /static/images/hero-bg.jpg HTTP/1.1" 200 95080
"GET /recording HTTP/1.1" 301 0
"GET /recording/ HTTP/1.1" 200 7
